<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="PendingRegistrations\Events\" />
    <Folder Include="PendingRegistrations\Exceptions\" />
    <Folder Include="PendingRegistrations\Handlers\" />
    <Folder Include="Users\Events\" />
    <Folder Include="Users\Handlers\" />
  </ItemGroup>

</Project>
